version: '3.9'

services:
  backend:
    container_name: kupipodariday-backend-container
    build:
      context: backend
      dockerfile: Dockerfile
    image: kupipodariday-backend-img
    ports:
      - 4000:3000
    env_file:
      - .env
  frontend:
    container_name: kupipodariday-frontend-container
    build:
      context: frontend
      dockerfile: Dockerfile
    image: kupipodariday-frontend-img
    ports:
      - 3005:80
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/data/postgres
  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8081:8080

volumes:
  postgres_data: